### model
model_name_or_path: Qwen/Qwen3-4B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_offload_config.json 

### dataset
dataset: qwen3_mr3_dataset_100k_easytohard_en_en
neat_packing: true
template: empty
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 0

### output
output_dir: saves/qwen3_4b_easytohard_en_en_1e5
logging_steps: 1
save_strategy: epoch
save_steps: null  # optional; can be omitted
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
